Enables #229

diff --git a/buildx/package.yaml b/buildx/package.yaml
--- a/buildx/package.yaml
+++ b/buildx/package.yaml
@@ -2,53 +2,54 @@ name: buildx
 description: Docker CLI plugin for extended build capabilities with BuildKit
 repo: docker/buildx
 links:
-- text: Docker CLI plugins proposal
-  url: https://github.com/docker/cli/issues/1534
+  - text: Docker CLI plugins proposal
+    url: https://github.com/docker/cli/issues/1534
 version:
   latest: v0.4.2 # renovate: datasource=github-releases depName=docker/buildx
   command: docker buildx version
   filter: ^github
   pattern: s/^github.com\/docker\/buildx\s(.+)\s.+$/\1/
 tags:
-- docker
-- container
-- build
-- builder
-- plugin
-- image
-install: |
-  : "${DOCKER_CLI_DIR:=${TARGET}/lib/docker/cli-plugins}"
-  : "${DOCKER_CONFIG:=${HOME}/.docker}"
+  - docker
+  - container
+  - build
+  - builder
+  - plugin
+  - image
+install:
+  script: |-
+    : "${DOCKER_CLI_DIR:=${TARGET}/lib/docker/cli-plugins}"
+    : "${DOCKER_CONFIG:=${HOME}/.docker}"
 
-  REQUIRED_DOCKER_VERSION=18.09
-  # Get smaller version of required and current version
-  DOCKER_VERSION=$(\
-      (\
-          docker version --format '{{.Client.Version}}'; \
-          echo "${REQUIRED_DOCKER_VERSION}"; \
-      ) | \
-      sort --version-sort | \
-      head -n 1; \
-  )
-  # if smaller version if required version
-  if test "${DOCKER_VERSION}" != "${REQUIRED_DOCKER_VERSION}"; then
-      echo "Error: Please install Docker >=${REQUIRED_DOCKER_VERSION}."
-      exit 1
-  fi
+    REQUIRED_DOCKER_VERSION=18.09
+    # Get smaller version of required and current version
+    DOCKER_VERSION=$(\
+        (\
+            docker version --format '{{.Client.Version}}'; \
+            echo "${REQUIRED_DOCKER_VERSION}"; \
+        ) | \
+        sort --version-sort | \
+        head -n 1; \
+    )
+    # if smaller version if required version
+    if test "${DOCKER_VERSION}" != "${REQUIRED_DOCKER_VERSION}"; then
+        echo "Error: Please install Docker >=${REQUIRED_DOCKER_VERSION}."
+        exit 1
+    fi
 
-  ${SUDO} mkdir --parents "${DOCKER_CLI_DIR}"
+    ${SUDO} mkdir --parents "${DOCKER_CLI_DIR}"
 
-  github_get_release docker/buildx | \
-      github_resolve_assets | \
-      github_select_asset_by_suffix .linux-amd64 | \
-      github_get_asset_download_url | \
-      download_file | \
-      store_file docker-buildx "${DOCKER_CLI_DIR}" | \
-      make_executable
+    github_get_release docker/buildx | \
+        github_resolve_assets | \
+        github_select_asset_by_suffix .linux-amd64 | \
+        github_get_asset_download_url | \
+        download_file | \
+        store_file docker-buildx "${DOCKER_CLI_DIR}" | \
+        make_executable
 
-  if ! test -f "${DOCKER_CONFIG}/config.json"; then
-      echo "{}" >"${DOCKER_CONFIG}/config.json"
-  fi
+    if ! test -f "${DOCKER_CONFIG}/config.json"; then
+        echo "{}" >"${DOCKER_CONFIG}/config.json"
+    fi
 
-  cp "${DOCKER_CONFIG}/config.json" "${DOCKER_CONFIG}/config.json.bak"
-  jq '. + {"experimental": "enabled"}' "${DOCKER_CONFIG}/config.json.bak" >"${DOCKER_CONFIG}/config.json"
+    cp "${DOCKER_CONFIG}/config.json" "${DOCKER_CONFIG}/config.json.bak"
+    jq '. + {"experimental": "enabled"}' "${DOCKER_CONFIG}/config.json.bak" >"${DOCKER_CONFIG}/config.json"
diff --git a/clip/package.yaml b/clip/package.yaml
--- a/clip/package.yaml
+++ b/clip/package.yaml
@@ -2,33 +2,34 @@ name: clip
 description: Docker Client Plugins Manager
 repo: lukaszlach/clip
 links:
-- text: Docker CLI plugins proposal
-  url: https://github.com/docker/cli/issues/1534
+  - text: Docker CLI plugins proposal
+    url: https://github.com/docker/cli/issues/1534
 tags:
-- docker
-- plugins
-install: |
-  : "${DOCKER_CLI_DIR:=${TARGET_BASE}/lib/docker/cli-plugins}"
+  - docker
+  - plugins
+install:
+  script: |-
+    : "${DOCKER_CLI_DIR:=${TARGET_BASE}/lib/docker/cli-plugins}"
 
-  REQUIRED_DOCKER_VERSION=19.03
-  # Get smaller version of required and current version
-  DOCKER_VERSION=$(\
-      (\
-          docker version --format '{{.Client.Version}}'; \
-          echo "${REQUIRED_DOCKER_VERSION}"; \
-      ) | \
-      sort --version-sort | \
-      head -n 1; \
-  )
-  # if smaller version if required version
-  if test "${DOCKER_VERSION}" != "${REQUIRED_DOCKER_VERSION}"; then
-      echo "Error: Please install Docker >=${REQUIRED_DOCKER_VERSION}."
-      exit 1
-  fi
+    REQUIRED_DOCKER_VERSION=19.03
+    # Get smaller version of required and current version
+    DOCKER_VERSION=$(\
+        (\
+            docker version --format '{{.Client.Version}}'; \
+            echo "${REQUIRED_DOCKER_VERSION}"; \
+        ) | \
+        sort --version-sort | \
+        head -n 1; \
+    )
+    # if smaller version if required version
+    if test "${DOCKER_VERSION}" != "${REQUIRED_DOCKER_VERSION}"; then
+        echo "Error: Please install Docker >=${REQUIRED_DOCKER_VERSION}."
+        exit 1
+    fi
 
-  ${SUDO} mkdir --parents "${DOCKER_CLI_DIR}"
+    ${SUDO} mkdir --parents "${DOCKER_CLI_DIR}"
 
-  echo "https://github.com/lukaszlach/clip/raw/master/docker-clip" | \
-      download_file | \
-      store_file docker-clip "${DOCKER_CLI_DIR}" |
-      make_executable
+    echo "https://github.com/lukaszlach/clip/raw/master/docker-clip" | \
+        download_file | \
+        store_file docker-clip "${DOCKER_CLI_DIR}" |
+        make_executable
